/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    posts: Post;
    services: Service;
    testimonials: Testimonial;
    recommendations: Recommendation;
    'use-cases': UseCase;
    'client-logos': ClientLogo;
    certifications: Certification;
    leads: Lead;
    subscribers: Subscriber;
    jobs: Job;
    'job-applications': JobApplication;
    'talent-profiles': TalentProfile;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    services: ServicesSelect<false> | ServicesSelect<true>;
    testimonials: TestimonialsSelect<false> | TestimonialsSelect<true>;
    recommendations: RecommendationsSelect<false> | RecommendationsSelect<true>;
    'use-cases': UseCasesSelect<false> | UseCasesSelect<true>;
    'client-logos': ClientLogosSelect<false> | ClientLogosSelect<true>;
    certifications: CertificationsSelect<false> | CertificationsSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    subscribers: SubscribersSelect<false> | SubscribersSelect<true>;
    jobs: JobsSelect<false> | JobsSelect<true>;
    'job-applications': JobApplicationsSelect<false> | JobApplicationsSelect<true>;
    'talent-profiles': TalentProfilesSelect<false> | TalentProfilesSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'hero-content': HeroContent;
    'about-content': AboutContent;
    'stats-content': StatsContent;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'hero-content': HeroContentSelect<false> | HeroContentSelect<true>;
    'about-content': AboutContentSelect<false> | AboutContentSelect<true>;
    'stats-content': StatsContentSelect<false> | StatsContentSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Describe this image for screen readers and SEO.
   */
  alt?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Blog posts shown in the Insights section.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  /**
   * URL-friendly identifier, e.g. "future-of-hr-strategy". Auto-generated from title.
   */
  slug: string;
  /**
   * Short summary (1–2 sentences) shown in post listings and SEO.
   */
  excerpt: string;
  heroImage?: (number | null) | Media;
  category: 'hr-strategy' | 'recruitment' | 'leadership' | 'culture' | 'mena' | 'career-tips';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  publishedAt?: string | null;
  /**
   * Estimated reading time. Auto-calculated if left blank.
   */
  readingTime?: number | null;
  /**
   * Override default SEO values for this post.
   */
  seo?: {
    /**
     * Defaults to post title if empty. Max 60 characters.
     */
    metaTitle?: string | null;
    /**
     * Defaults to excerpt if empty. Max 160 characters.
     */
    metaDescription?: string | null;
    /**
     * Defaults to cover image. Recommended: 1200×630px.
     */
    ogImage?: (number | null) | Media;
    noIndex?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Manage the service cards shown on the Services and Home pages.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services".
 */
export interface Service {
  id: string;
  title: string;
  /**
   * Shown on the Home page card (1–2 sentences).
   */
  shortDescription: string;
  /**
   * Full detail shown on the Services page.
   */
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  icon:
    | 'growth-readiness'
    | 'fractional-chro'
    | 'org-design'
    | 'leadership-advisory'
    | 'executive-search'
    | 'hr-consulting'
    | 'recruitment'
    | 'org-development'
    | 'training'
    | 'strategy'
    | 'people';
  /**
   * Bullet points of key deliverables for this service.
   */
  highlights?:
    | {
        point: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Client testimonials and success stories.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials".
 */
export interface Testimonial {
  id: string;
  clientName: string;
  /**
   * e.g. "CEO", "Head of People"
   */
  role?: string | null;
  company?: string | null;
  /**
   * The full testimonial text (2–4 sentences recommended).
   */
  quote: string;
  photo?: (number | null) | Media;
  order?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Professional recommendations (e.g. LinkedIn) shown on the Recommendations page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recommendations".
 */
export interface Recommendation {
  id: string;
  name: string;
  /**
   * e.g. "Chief Executive Officer".
   */
  role?: string | null;
  company?: string | null;
  /**
   * e.g. "Worked with H++ on org redesign".
   */
  relationship?: string | null;
  /**
   * The full recommendation text.
   */
  quote: string;
  linkedinUrl?: string | null;
  photo?: (number | null) | Media;
  order?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Anonymised client scenarios shown in the Use Cases section and page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "use-cases".
 */
export interface UseCase {
  id: string;
  /**
   * e.g. "Scaling a fintech from 40 to 200 people".
   */
  title: string;
  /**
   * e.g. "Technology", "Retail & FMCG".
   */
  industry?: string | null;
  /**
   * The people/organization problem the client faced.
   */
  challenge: string;
  /**
   * How H++ addressed it (optional, shown on the detail page).
   */
  solution?: string | null;
  /**
   * The measurable outcome. Lead with a number where possible.
   */
  result: string;
  icon?: ('scaling' | 'leadership' | 'structure') | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Client / partner logos shown in the "Trusted by" strip and Clients page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-logos".
 */
export interface ClientLogo {
  id: string;
  /**
   * Used as the logo alt text and as a text fallback if no image is set.
   */
  name: string;
  /**
   * Transparent PNG/SVG preferred. Displayed in grayscale, colour on hover.
   */
  logo?: (number | null) | Media;
  website?: string | null;
  order?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Professional certifications and badges shown on the About page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications".
 */
export interface Certification {
  id: string;
  name: string;
  issuer: string;
  year?: number | null;
  badgeImage?: (number | null) | Media;
  /**
   * Link to verify this certification online.
   */
  verifyUrl?: string | null;
  order?: number | null;
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Contact form submissions from the website.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: string;
  name: string;
  email: string;
  company?: string | null;
  topic?: ('hr-consulting' | 'recruitment' | 'training' | 'general') | null;
  message: string;
  status?: ('new' | 'in-progress' | 'replied' | 'archived') | null;
  /**
   * Which page the form was submitted from.
   */
  source?: string | null;
  /**
   * Private notes — not visible to the lead.
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Newsletter subscribers.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers".
 */
export interface Subscriber {
  id: string;
  email: string;
  name?: string | null;
  status?: ('active' | 'unsubscribed') | null;
  source?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Job listings shown in the Careers portal.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs".
 */
export interface Job {
  id: string;
  title: string;
  /**
   * Auto-generated from title. e.g. "senior-hr-business-partner-dubai"
   */
  slug: string;
  /**
   * Visible company name. Use "Confidential" to hide client identity.
   */
  company?: string | null;
  /**
   * e.g. "Dubai, UAE" or "Remote – MENA"
   */
  location?: string | null;
  employmentType: 'full-time' | 'part-time' | 'contract' | 'freelance' | 'internship';
  industry:
    | 'technology'
    | 'finance'
    | 'healthcare'
    | 'real-estate'
    | 'retail'
    | 'manufacturing'
    | 'education'
    | 'hospitality'
    | 'hr-consulting'
    | 'other';
  experienceLevel: 'entry' | 'mid' | 'senior' | 'executive';
  /**
   * e.g. "AED 15,000–20,000/month" — leave blank if not disclosed.
   */
  salaryRange?: string | null;
  applicationDeadline?: string | null;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  requirements?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  benefits?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  isActive?: boolean | null;
  /**
   * Lower numbers appear first.
   */
  order?: number | null;
  /**
   * Override default SEO for this job listing.
   */
  seo?: {
    /**
     * Defaults to job title + company if empty.
     */
    metaTitle?: string | null;
    /**
     * Max 160 characters.
     */
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Applications submitted through the Careers portal.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-applications".
 */
export interface JobApplication {
  id: string;
  job: number | Job;
  applicantName: string;
  email: string;
  phone?: string | null;
  linkedIn?: string | null;
  coverLetter?: string | null;
  cv?: (number | null) | Media;
  status?: ('new' | 'reviewing' | 'shortlisted' | 'rejected' | 'hired') | null;
  /**
   * Visible to admins only. Not shared with the applicant.
   */
  adminNotes?: string | null;
  appliedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Candidates who registered via the "Be Found" talent form. Seeds the Phase 3 talent pool.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "talent-profiles".
 */
export interface TalentProfile {
  id: string;
  name: string;
  email: string;
  phone?: string | null;
  /**
   * e.g. "Senior HR Business Partner | 8 Years MENA Experience"
   */
  headline?: string | null;
  industry?:
    | (
        | 'technology'
        | 'finance'
        | 'healthcare'
        | 'real-estate'
        | 'retail'
        | 'manufacturing'
        | 'education'
        | 'hospitality'
        | 'hr-consulting'
        | 'other'
      )
    | null;
  experienceLevel?: ('entry' | 'mid' | 'senior' | 'executive') | null;
  /**
   * Add up to 10 key skills.
   */
  skills?:
    | {
        skill: string;
        id?: string | null;
      }[]
    | null;
  region?: ('uae' | 'ksa' | 'egypt' | 'qatar' | 'kuwait' | 'bahrain' | 'jordan' | 'lebanon' | 'mena' | 'remote') | null;
  linkedIn?: string | null;
  cv?: (number | null) | Media;
  isVisible?: boolean | null;
  submittedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'posts';
        value: number | Post;
      } | null)
    | ({
        relationTo: 'services';
        value: number | Service;
      } | null)
    | ({
        relationTo: 'testimonials';
        value: number | Testimonial;
      } | null)
    | ({
        relationTo: 'recommendations';
        value: number | Recommendation;
      } | null)
    | ({
        relationTo: 'use-cases';
        value: number | UseCase;
      } | null)
    | ({
        relationTo: 'client-logos';
        value: number | ClientLogo;
      } | null)
    | ({
        relationTo: 'certifications';
        value: number | Certification;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'subscribers';
        value: number | Subscriber;
      } | null)
    | ({
        relationTo: 'jobs';
        value: number | Job;
      } | null)
    | ({
        relationTo: 'job-applications';
        value: number | JobApplication;
      } | null)
    | ({
        relationTo: 'talent-profiles';
        value: number | TalentProfile;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  heroImage?: T;
  category?: T;
  content?: T;
  publishedAt?: T;
  readingTime?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
        noIndex?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "services_select".
 */
export interface ServicesSelect<T extends boolean = true> {
  title?: T;
  shortDescription?: T;
  description?: T;
  icon?: T;
  highlights?:
    | T
    | {
        point?: T;
        id?: T;
      };
  order?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "testimonials_select".
 */
export interface TestimonialsSelect<T extends boolean = true> {
  clientName?: T;
  role?: T;
  company?: T;
  quote?: T;
  photo?: T;
  order?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recommendations_select".
 */
export interface RecommendationsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  company?: T;
  relationship?: T;
  quote?: T;
  linkedinUrl?: T;
  photo?: T;
  order?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "use-cases_select".
 */
export interface UseCasesSelect<T extends boolean = true> {
  title?: T;
  industry?: T;
  challenge?: T;
  solution?: T;
  result?: T;
  icon?: T;
  order?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "client-logos_select".
 */
export interface ClientLogosSelect<T extends boolean = true> {
  name?: T;
  logo?: T;
  website?: T;
  order?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "certifications_select".
 */
export interface CertificationsSelect<T extends boolean = true> {
  name?: T;
  issuer?: T;
  year?: T;
  badgeImage?: T;
  verifyUrl?: T;
  order?: T;
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  company?: T;
  topic?: T;
  message?: T;
  status?: T;
  source?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "subscribers_select".
 */
export interface SubscribersSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  status?: T;
  source?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "jobs_select".
 */
export interface JobsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  company?: T;
  location?: T;
  employmentType?: T;
  industry?: T;
  experienceLevel?: T;
  salaryRange?: T;
  applicationDeadline?: T;
  description?: T;
  requirements?: T;
  benefits?: T;
  isActive?: T;
  order?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "job-applications_select".
 */
export interface JobApplicationsSelect<T extends boolean = true> {
  job?: T;
  applicantName?: T;
  email?: T;
  phone?: T;
  linkedIn?: T;
  coverLetter?: T;
  cv?: T;
  status?: T;
  adminNotes?: T;
  appliedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "talent-profiles_select".
 */
export interface TalentProfilesSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  phone?: T;
  headline?: T;
  industry?: T;
  experienceLevel?: T;
  skills?:
    | T
    | {
        skill?: T;
        id?: T;
      };
  region?: T;
  linkedIn?: T;
  cv?: T;
  isVisible?: T;
  submittedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Global site configuration — logo, contact details, social links.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  siteName: string;
  tagline?: string | null;
  logo?: (number | null) | Media;
  favicon?: (number | null) | Media;
  email?: string | null;
  phone?: string | null;
  location?: string | null;
  linkedin?: string | null;
  twitter?: string | null;
  /**
   * Used for "Book a Call" buttons across the site.
   */
  bookingUrl?: string | null;
  /**
   * Include country code, digits only. E.g. 971501234567 for UAE. Leave empty to hide the widget.
   */
  whatsapp?: string | null;
  defaultMetaTitle?: string | null;
  defaultMetaDescription?: string | null;
  defaultOgImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Controls the main hero banner on the Home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-content".
 */
export interface HeroContent {
  id: string;
  /**
   * Main large heading. Keep it powerful and short.
   */
  headline: string;
  subtext?: string | null;
  primaryCtaLabel?: string | null;
  secondaryCtaLabel?: string | null;
  /**
   * Professional headshot. Shown in the hero section.
   */
  portrait?: (number | null) | Media;
  identityTitle?: string | null;
  aboutLinkLabel?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Bio, mission, and values shown on the About page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-content".
 */
export interface AboutContent {
  id: string;
  pageTitle?: string | null;
  /**
   * Full professional background and story.
   */
  bio: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Core mission in 1–2 sentences. Shown prominently on the About page.
   */
  missionStatement?: string | null;
  values?:
    | {
        title: string;
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Short differentiator statements shown on Home and About.
   */
  whyPoints?:
    | {
        point: string;
        id?: string | null;
      }[]
    | null;
  ctaLabel?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Social proof numbers shown on the Home page.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats-content".
 */
export interface StatsContent {
  id: string;
  isVisible?: boolean | null;
  /**
   * Each stat appears as a number + label pair.
   */
  stats?:
    | {
        value: string;
        label: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  tagline?: T;
  logo?: T;
  favicon?: T;
  email?: T;
  phone?: T;
  location?: T;
  linkedin?: T;
  twitter?: T;
  bookingUrl?: T;
  whatsapp?: T;
  defaultMetaTitle?: T;
  defaultMetaDescription?: T;
  defaultOgImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero-content_select".
 */
export interface HeroContentSelect<T extends boolean = true> {
  headline?: T;
  subtext?: T;
  primaryCtaLabel?: T;
  secondaryCtaLabel?: T;
  portrait?: T;
  identityTitle?: T;
  aboutLinkLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-content_select".
 */
export interface AboutContentSelect<T extends boolean = true> {
  pageTitle?: T;
  bio?: T;
  missionStatement?: T;
  values?:
    | T
    | {
        title?: T;
        description?: T;
        id?: T;
      };
  whyPoints?:
    | T
    | {
        point?: T;
        id?: T;
      };
  ctaLabel?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "stats-content_select".
 */
export interface StatsContentSelect<T extends boolean = true> {
  isVisible?: T;
  stats?:
    | T
    | {
        value?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}